### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

### PR DESCRIPTION
**Pull request by dpryan79**
R 3.5.1

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@dpryan79 can you help out the r-base recipe?  Once thats landed these all happen magically.

**Comment by dpryan79** [comment]
@mariusvniekerk Sure? I wasn't aware that there were r-base recipe issues still.

**Comment by dpryan79** [comment]
@mariusvniekerk Are you thinking of this issue in particular? https://github.com/conda-forge/r-base-feedstock/issues/49

**Comment by bgruening** [comment]
@dpryan79 this one here: https://github.com/conda-forge/r-base-feedstock/pull/57
I minged @mingwandroid as he wanted to work on this, otherwise I can also try to give it a try this evening.

**Comment by dpryan79** [comment]
Eeek, that needs much more than I know about building things on Windows.

**Pull request merged**
